example_project/example_project/settings.py
This has moved in 1.9, and defaults to the DEBUG setting anyway
=> Remove TEMPLATE_DEBUG setting. Fixes #57

players/static/js/watch/world-viewer.js, players/templates/players/watch.html, players/views.py
- made player key available in the `watch` template context
- user can identify their own avatar via the presence of (currently) a red square.
=> Added icon to the avatar of the current user. Fixes #120.

aimmo-game/service.py, aimmo-game/simulation/action.py, aimmo-game/simulation/avatar/avatar_manager.py, aimmo-game/simulation/avatar/avatar_wrapper.py, aimmo-game/simulation/direction.py, aimmo-game/simulation/game_state.py, aimmo-game/simulation/map_generator.py, aimmo-game/simulation/turn_manager.py, aimmo-game/simulation/world_map.py, aimmo-game/tests/simulation/dummy_avatar.py, aimmo-game/tests/simulation/maps.py, aimmo-game/tests/simulation/test_action.py, aimmo-game/tests/simulation/test_game_state.py, aimmo-game/tests/simulation/test_turn_manager.py, aimmo-game/tests/simulation/test_worker_manager.py, aimmo-game/tests/simulation/test_world_map.py, aimmo-game/tests/test_service.py
- `run_turn` now performs each worker request in a new thread
- actions are registered on the world map before they are applied
- once all actions are registered, actions are applied in this order:
- wait actions
- attack actions
- move actions
- avatars may be attacked in both their current location and their new location
- if two or more avatars attempt to move to the same location, they all fail
=> Concurrent turns

aimmo-game-creator/service.py, aimmo-reverse-proxy/Dockerfile, aimmo-reverse-proxy/deploy-aimmo-reverse-proxy.yaml, aimmo-reverse-proxy/ingress.yaml, aimmo-reverse-proxy/nginx.conf, aimmo-reverse-proxy/service-aimmo-reverse-proxy.yaml
* Run a nginx pod which does the same job ingress was doing but use the Kubernetes DNS instead of updating with aimmo-game-creator.
* Add this pod to a static ingress.
Config that will need updating:
* Add the new image to Docker Hub.
* Launch the new pod in the update script.
* Update the DNS alias for staging.aimmo.codeforlife.education to point to the new ingress IP
=> Replace Ingress with a reverse proxy

aimmo-game/service.py
As not testing via django-setuptest anymore the catch for eventlet monkey patching can be removed.
=> Enable eventlet even during testing

aimmo-game-worker/initialise.py, aimmo-game-worker/service.py, aimmo-game/simulation/turn_manager.py, aimmo-game/simulation/worker_manager.py
* If there is a crash during the `TurnManager` main loop log it but keep running (previously the exception was uncaught which means the game would crash).
* Add logging in workers.
* Wait for workers to be running before trying to get their IP. (Otherwise causes crash.)
=> Add better error handling and logging

players/templates/players/watch.html
Socket.io URL cdn.socket.io no longer available - changed source to cdnjs
=> Updated Socket.io source

aimmo-game-worker/simulation/location.py, aimmo-game-worker/simulation/world_map.py, aimmo-game/simulation/location.py, aimmo-game/simulation/world_map.py, aimmo-game/tests/test_simulation/test_game_state.py, aimmo-game/tests/test_simulation/test_location.py, aimmo-game/tests/test_simulation/test_map_generator.py
Location implements __eq__, but not __ne__, which means if comparing two locations that are the same `a == b` returns True, and `a != b` also returns True (because the default is object identity, rather than the negation of the __eq__ method. Sigh.
Fixed by implementing __ne__.
Also made map_generator tests deterministic (`random.seed(0)`).
=> fix #163 and other __ne__ issues

aimmo-game-creator/setup.py, aimmo-game-creator/tests/test_worker_manager.py, aimmo-game-worker/tests/simulation/test_location.py, aimmo-game/tests/test_simulation/avatar/test_fog_of_war.py, aimmo-game/tests/test_simulation/test_location.py, aimmo-game/tests/test_simulation/test_turn_manager.py
After yesterday's (04/09/2017) issues with rebasing and merging my pull request became obsolete and I was unable to get it back into a working state.
Instead I forked out from master again and cherry picked relevant commits. They're also squashed and all changes are applied as suggested in #227.
I will now close #227.
=> Fixed Test Coverage PR #227

aimmo-game/simulation/action.py, aimmo-game/simulation/avatar/avatar_view.py, aimmo-game/simulation/avatar/fog_of_war.py, aimmo-game/simulation/custom_map.py, aimmo-game/simulation/direction.py, aimmo-game/simulation/game_state.py, aimmo-game/simulation/map_generator.py, aimmo-game/simulation/turn_manager.py, aimmo-game/simulation/worker_manager.py, aimmo-game/simulation/world_map.py, aimmo-game/tests/test_simulation/avatar/test_fog_of_war.py, aimmo-game/tests/test_simulation/test_world_map.py, integration-tests/tests/test_backend.py, integration-tests/tests/test_end_to_end.py
Some code PEP8 fixes as well as refactoring when I was reading the codebase trying to get hang of it ;)
=> Refactoring and PEP8 fixes.

aimmo-game/simulation/avatar/avatar_wrapper.py, aimmo-game/simulation/custom_map.py, aimmo-game/simulation/pickups.py, aimmo-game/tests/test_simulation/test_custom_map.py, aimmo-game/tests/test_simulation/test_pickups.py
I decided to make multiple pull requests as the whole change of the codebase will be quite lengthy. 
**Changes Made:**
- `HealthPickup`, `InvulnerabilityPickup` and `DamagePickup` removed.
- Slowly removing effects from the codebase, `_PickupEffect` from `pickups.py` is gone.
- `JSONDecoder` changed to only decode the one type of pickup now.
-  Uses of the above removed throughout the codebase, including:
- - `custom_map.py`, `test_pickups.py`, `test_simulation.py`, `test_pickup_decoder()` , `test_custom_map` and `ALL_PICKUPS`
- New test written.
=> Level 1 Minimum Product: Pickups

aimmo-game/simulation/world_map.py, aimmo-game/tests/test_simulation/test_world_map.py
Ported `world_map` and `test_world_map` to python3, ie:
- `xrange` is now replaced is `range`.
- `try` and `except` used in instances where `itervalues()` is used. This way I can allow for both versions to run the code.
=> Minimum Product: World map ported to python3.

aimmo-game/simulation/avatar/avatar_view.py, aimmo-game/simulation/levels/parsers.py, aimmo-game/tests/test_service.py, aimmo-game/tests/test_simulation/avatar/test_avatar_wrapper.py, aimmo-game/tests/test_simulation/test_map_generator.py, aimmo-game/tests/test_simulation/test_worker_manager.py
**Issue #265 fix:**
- Changed all instances of `xrange` to `range`.
- Found a use of `unicode` which is replaced by `str` (technically).
**Refactoring:**
- Removed an unused import.
- Changed a set function call in a test to a set literal. [Twice as fast execution.](https://renzo.lucioni.xyz/pythons-set-literals/)
=> Ported game package to py3.

aimmo-game/simulation/pickups.py, aimmo-game/tests/test_simulation/test_pickups.py
Initial dig at writing more extensive unit pickup tests. Coverage of the file was fine but they clearly weren't tested well enough. I'm new to tests so criticize as much as you can :P
- `HealthPickup` has now certain constraints. It can't be equal to or less than 0, and can't be greater than 100.
- If the pickup added to the avatar health will be greater than 100, cap it at 100hp.
- DamagePickup can be now specified with the custom damage boost.
- Pickups are more testable. You can make use of `set_custom_pickup` to add your own params as opposed to using only default ones.
- Extra tests.
Please test extensively before approving. We **don't** have integration tests anymore. Use the manual test plan to get an idea of things that need to be checked.
=> Pickup Tests

.gitignore, aimmo-game/simulation/effects.py, aimmo-game/simulation/pickups.py, aimmo-game/tests/functional/test_damage_pickups_and_effects.py, aimmo-game/tests/functional/test_health_pickups_and_effects.py, aimmo-game/tests/functional/test_invulnerability_pickups_and_effects.py, setup.py
We're starting to do some property based testing and it's turning out to be great! I'm using [hypothesis](http://hypothesis.readthedocs.io/en/latest/) to do some simple changes and it's working out great.
Hypothesis has found some errors in our code that need to be considered. One of them is how we treat infinite values as method parameters in places.
An error may look like this and you can use the seed to reproduce the issue. It really is amazing ;)
Therefore, this PR:
- `DamageBoostPickupEffect` ensures that infinity gets casted into the maximum possible int.
- `DamageBoostPickup` checks whether the boost value is > 0 now. 
- Damage pickups and health pickups now use hypothesis ;)))
- Dependency added to `setup.py`
=> Hypothesis initial

.github/stale.yml
Adds [stale app](https://probot.github.io/apps/stale/) settings to our project.
We have agreed on the following:
- **Two months of inactivity to review** stale issues.
- **Two weeks** of inactivity after request for review for issue to be marked as **stale** and closed.
- **Comment is added**
=> Add stale.yml to indicate integration with the stale app

aimmo-game-creator/rc-aimmo-game-creator.yaml, aimmo_runner/minikube.py
Minor change that removes the link from the yaml to the staging server and replaces it with a "REPLACE_ME" string. 
The value is always replaced by the logic in minikube.py, so the initial default makes no functionality difference; this is only to avoid further confusion.
Not tested, but should not change anything.
=> Remove staging link to avoid confusion at minikube level

aimmo-game-creator/rc-aimmo-game-creator.yaml, aimmo-game-creator/tests/test_aimmo_game_creator_yaml.py, aimmo-game-creator/worker_manager.py, aimmo_runner/minikube.py, aimmo_runner/tests/test_minikube_runner.py, players/templates/players/watch.html, players/tests.py, players/urls.py, players/views.py
This PR will do the following:
- Fixes a URL resolution issue that was missed out on earlier locally. 
- When unity is loaded, we call our newly made function.
- That function will send an AJAX request, also created in the PR, to an API url for that game, and return a JSON.
- We parse the ID from the JSON, send it to the `World Controller`, which is not set up yet - therefore omitted by unity.
- Tests added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/501)
=> Logic to distinguish current avatar ID serverside

docs/usage.md
The link to the Installing virtualenvwrapper on mac was incorrect. This points it to the right place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/527)
=> Correct markdown link for mac installation

aimmo-game-creator/worker_manager.py, docs/deployment/nginx-setup.md
Part of #570. Might be worth reading.
This PR will decrease a **reserved** quantity of CPU by each `aimmo-game` meaning we can spawn more than our testing has shown (staging proved to be no more than 11-12 games with 1 player each at previous amounts). 
The value `10m` is equivalent to 1% of the CPU power we have on GCE. This is currently 3x nodes of 1vCPU each. Therefore it's 1% of one 1vCPU. 
In simple terms this means that we can probably run around a maximum of 110 games right now.
Another thing this changes is the limit. This means that even with the maximum amount of games requested (allocated) the games can request up to 30% of the vCPU when required. Therefore under massive loads (for the game, not the worker) things can get slow. We first need to assess if they will ever get to …
=> Optimise used resources by k8s

aimmo-game/simulation/worker_manager.py
This will be an ongoing process because of #586 unfortunately. Until that is solved there will be many PR's coming in.
From the statistics I've seen, these should work fine for now.
Another problem we have is the amount of nodes we run in parallel. They're not very powerful CPU wise, and standalone k8s already takes about half of the mCPU available. We run things like heapster on there. Solution would be to get more powerful individual machines, not scale sideways. Plus loads of other things, but that's for later ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/587)
=> Further optimisations of k8s

aimmo-game-creator/game_manager.py
After one of the recent PR's we have had an issue where a parameter was left unset leaving an incorrect ingress yaml on our deployment servers. This should solve that.
Tests seem irrelevant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/591)
=> Fix "none" service port in ingress

game_frontend/jsconfig.json, game_frontend/package.json, game_frontend/src/redux/store.js, game_frontend/src/testHelpers/createShallow.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/641)
=> Document createShallowWithTheme

aimmo_runner/runner.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/642)
=> Make aimmo compatible with Django 1.9

setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/643)
=> Using patch version of Django 1.9

docs/usage.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/664)
=> Fixed ubuntu_setup command so the script can be run with sudo

aimmo-game/simulation/worker_managers/__init__.py, aimmo-game/simulation/worker_managers/local_worker_manager.py
Small mistake in previous PR where LocalWorkerManager was used in place in K8sWorkerManager and vice-versa.
Fixes #668.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/669)
=> OsError worker_manager bug

aimmo-game-worker/avatar_runner.py, aimmo-game-worker/service.py, aimmo-game-worker/tests/test_avatar_runner.py, aimmo/avatar_examples/attacking_avatar.py, aimmo/avatar_examples/dumb_avatar.py, aimmo/avatar_examples/health_seeker_avatar.py, aimmo/avatar_examples/winner_avatar.py
As described in #673. Does some changes to how we catch errors, refactors method names and (please check) flips method params around because I thought they were wrong.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/674)
=> Fix #673 - error catching bug

aimmo/urls.py, example_project/example_project/settings.py
RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got django_js_reverse.views.urls_js). Pass the callable instead.
(1_10.W001) The MIDDLEWARE_CLASSES setting is deprecated in Django 1.10 and the MIDDLEWARE setting takes precedence. Since you've set MIDDLEWARE, the value of MIDDLEWARE_CLASSES is ignored.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/682)
=> Fixed deprecation warnings for Django 1.10

aimmo_runner/runner.py
This is something that was there before when we upgraded from django 1.9 -> 1.10 but must have gotten removed in a revert/rebase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/687)
=> add django.setup() (needed in django 1.10)

aimmo-game-creator/game_manager.py, aimmo-game-creator/rc-aimmo-game-creator.yaml, aimmo-game/simulation/worker_managers/kubernetes_worker_manager.py
Please read #689 before reviewing!
This PR will increase our pod security from kubesec rating 7 to 8. The next step would be to completely remove root access, but that was quite difficult to figure out as we don't assign and uID or gIDs right now.
A simple scan of existing game pods for example:
```
(aimmo-UXHtE3Rq) bash-3.2$ kubectl -n default plugin scan pod/game-1-zzn2n
scanning pod game-1-zzn2n
pod/game-1-zzn2n kubesec.io score 8
```
The advisory is now gone.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/690)
=> Restrict kubernetes pod kernel capabilities

aimmo-game-worker/avatar_runner.py, aimmo-game-worker/service.py, aimmo-game-worker/tests/test_avatar_runner.py
Fixes https://github.com/ocadotechnology/aimmo/issues/696
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/697)
=> Now catch any serialise errors

aimmo/game_renderer.py
Fixes #694. Please read the issue if you're reviewing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/695)
=> Fix local non -k mode

Pipfile, Pipfile.lock
I regenerated the `Pipfile.lock` using `pipenv lock` command. I think we should be more careful in future to ensure that the lock does not get out of date.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/708)
=> Updated pipfile.lock

aimmo-game-worker/requirements.txt, aimmo-game-worker/setup.py
When `pykube` was removed from `requirements.txt` this resulted in an `ImportError` for the `requests` module. This is because `requests` was a dependency in our project (and in `pykube`), but not listed in `requirements.txt`. We should consider using `pipenv` in our containers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/717)
=> Added requests to requirements.txt

aimmo-game-creator/requirements.txt
According to the k8s python-client changelog (https://github.com/kubernetes-client/python/blob/master/CHANGELOG.md), `delete_namespaced_service` takes a body parameter in version 6.0. This fixes https://github.com/ocadotechnology/aimmo/issues/718. Has been tested on dev.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/719)
=> upgrade k8s requirements

game_frontend/src/components/IDEEditor/index.js
Now that IDE is an container, a change in `state.consoleLog.logs` was causing a re-render in `IDEEditor`.
To stop this I have made IDEEditor a PureComponent to reflect that it only derives itself from props
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/723)
=> Only re-render `IDEEditor` component if props change

aimmo-game/service.py, aimmo-game/tests/test_socketio.py
This PR means that if the logs are the empty string or `None`, we no longer emit them on the socket. This stops extra empty lines being printed on the front end.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/732)
=> Don't send empty logs

game_frontend/src/containers/IDE/__snapshots__/index.test.js.snap, game_frontend/yarn.lock
The builds were seen to be failing because for some reason (which we can't explain without digging into it) as `<React.Fragment>` was replaced by `<Fragment>`.
This replaces that in the snapshot to make them pass again and while I was at it I upgraded all deps to match `package.json`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/775)
=> Update yarn.lock & snapshot test

aimmo/game_renderer.py, aimmo/tests/tests.py, aimmo/views.py
The function get_avatar_id_from_user_id() is passing in a user_id to can_user_play() but this function requires a User object.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/779)
=> Changed get_avatar_id_from_user_id() to get_avatar_id_from_user()

aimmo-game/service.py
created a copy of the dictionary to be used instead of original when iterating, this way if the dictionary mutates it won't affect the iterator.
fix: https://github.com/ocadotechnology/aimmo/issues/762
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/791)
=> add lines to prevent dict from mutating while being iterated over

Pipfile, Pipfile.lock, aimmo-game-worker/avatar_runner.py, aimmo-game-worker/setup.py, aimmo-game-worker/simulation/action.py, aimmo-game-worker/tests/test_avatar_runner.py, aimmo-game-worker/user_exceptions.py
Added custom exception to make console output more readable when user creates an invalid action.
Fixes https://github.com/ocadotechnology/aimmo/issues/771
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/789)
=> add custom exception for invalid action

ubuntu_setup.sh
Minor fix which confused `cmdtest` with `yarn`. More info in #801.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/802)
=> Ubuntu setup script fix

aimmo_runner/minikube.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/846)
=> Update minikube status check

aimmo-game-worker/avatar_runner.py, aimmo-game-worker/tests/test_avatar_runner.py, aimmo-game/tests/test_simulation/dummy_avatar.py, aimmo-game/tests/test_simulation/mock_communicator.py, aimmo/avatar_examples/attacking_avatar.py, aimmo/avatar_examples/health_seeker_avatar.py, aimmo/avatar_examples/simple_avatar.py, aimmo/avatar_examples/winner_avatar.py, docs/architecture/workers/README.md, docs/testing/test-plan.md
Default code now looks like this:
```python
class Avatar:
def next_turn(self, world_state, avatar_state):
return MoveAction(direction.NORTH)
```
as per issue requirements. I kept the functionality for the original handle_turn method as well so existing games will still function for now as it was a relatively simple tweak to the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/962)
=> replace handle_turn with next_turn

docs/architecture/README.md, docs/usage.md, game_frontend/README.md
Removed Unity build instructions from architecture README.md, usage.md and game-frontend README.md.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1128)
=> fix: removed unity instructions from docs

.travis.yml
`version_updater.py` imports a function from `semantic-release` and it failed as it was only installed at a later stage in Travis. This PR fixes this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1131)
=> ci: installing semantic release in the release stage

.travis.yml, version_updater.py
Remove the TRAVIS_PULL_REQUEST_BRANCH arg as the release stage will never run on a PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1135)
=> ci: simplify version updater

.travis.yml, version_updater.py
The last attempt at creating a tag appended the version with 'dev' because the check on the boolean `DEPLOY_TO_DEV` just checked if the env var existed, as opposed to checking that it equalled true.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1137)
=> ci: fix check for deploying to dev

.travis.yml
There was a problem whereby the docker images on staging and dev could not be pulled properly. It seemed like this was because of the version tag being different on DockerHub and in Pypi: Travis built and pushed a tag on DockerHub with a 'v' but the images that were being pulled from the creator for example depended on the version on Pypi which doesn't have a 'v'.
This PR should fix this by making Travis push tags on DockerHub without the 'v' which should match the Pypi versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1152)
=> fix: remove 'v' from Travis tag in docker commands

aimmo-game/activity_monitor.py, aimmo-game/service.py, aimmo-game/simulation/game_runner.py, aimmo-game/simulation/worker_manager.py, aimmo-game/simulation/workers/worker.py, aimmo-game/tests/test_simulation/concrete_worker.py, aimmo-game/tests/test_simulation/mock_worker_manager.py, aimmo-game/tests/test_simulation/workers/test_local_worker.py, aimmo-game/tests/test_socketio.py
By switching the `parallel_map` function to use asyncio, we lost the ability to execute the synchronous adding worker code concurrently. This PR reverts to how it was done before (using a `ThreadPoolExecutor`) and also includes some changes to make the log messages cleaner.
> **Note**
> As before, this still doesn't guarantee that the turn time will 2 seconds if adding workers takes longer than that. However, at least this way it is faster than before so that it is less noticeable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1182)
=> fix: add, update and remove workers concurrently

aimmo-game/Pipfile.lock, aimmo-game/setup.py
This PR reverts the Pipfile.lock file to what it was in version 0.31.1 (latest working version, as shown by the fact that production is working). The only dependency which hasn't been reverted in pytest, still on 5.2.2.
This has been tested locally. It was indeed the fact that the Pipfile had been updated and pushed to development, effectively **updating all dependencies in the aimmo-game environment** which caused the connection error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1202)
=> fix: revert version to fix connection issue

game_frontend/src/components/ConsoleBar/__snapshots__/index.test.js.snap, game_frontend/src/components/ConsoleBar/index.js, game_frontend/src/containers/IDEConsole/index.js, game_frontend/src/redux/features/Editor/actions.js, game_frontend/src/redux/features/Editor/epics.js, game_frontend/src/redux/features/Editor/reducers.js, game_frontend/src/redux/features/Editor/reducers.test.js, game_frontend/src/redux/features/Editor/types.js, game_frontend/src/redux/features/constants.js
This PR implements the reset code button in Kurono.
This button resets the user's code to the default code when pressed.
This PR also includes a test and an analytics event for that button.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1248)
=> feat: Implement reset code button

aimmo-game/simulation/game_runner.py
This PR addresses the issue linked below by forcing the loop to crash in case of an Exception.
Two things we need to discuss:
- Should we keep this generic Exception catching or should we target a more specific Exception?
- What should the logger message say?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1301)
=> fix: Stop loop on Exception in game turn

aimmo-game-worker/setup.py
Adding this kwarg because the current package doesn't have the `simulation` sub-package.
https://packaging.python.org/guides/distributing-packages-using-setuptools/#packages
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1333)
=> fix: Add include kwarg to find_packages

Pipfile.lock, aimmo-game/Pipfile, aimmo-game/Pipfile.lock, aimmo-game/simulation/avatar/avatar_manager.py, aimmo-game/simulation/game_state.py, aimmo-game/simulation/obstacle.py, aimmo-game/simulation/simulation_runner.py, aimmo-game/simulation/worksheet/__init__.py, aimmo-game/simulation/worksheet/worksheet.py, aimmo-game/tests/test_simulation/test_simulation_runner.py
Because of Agones changes, aimmo-game doesn't load the correct worksheet ID at the moment. This is fine for now as worksheets 1 and 2 have the same data, but it will be needed for the third one which will have different properties.
Note this won't work if the game worksheet is changed after the game is running - we will fix this at a later stage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1476)
=> fix: load correct worksheet in aimmo-game

aimmo/game_manager.py, aimmo/serializers.py, aimmo/tests/test_game_manager.py, aimmo/tests/test_views.py, example_project/example_project/settings.py
Duplicated part of game_manager in aimmo. Game server now gets recreated when a game worksheet gets updated.
Tested locally by changing the worksheet on a running game server, playing it and checking the worksheet is updated. Also tested this on a stopped server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1487)
=> fix: Fix worksheets not changing on game server

.github/workflows/cicd.yml, Pipfile, Pipfile.lock, example_project/example_project/settings.py, game_frontend/.eslintrc.js, game_frontend/djangoBundler.js, game_frontend/public/handlebars_template.html, game_frontend/src/global.d.ts, game_frontend/src/index.js, game_frontend/src/redux/features/Analytics/epics.js, game_frontend/src/redux/features/Analytics/epics.test.js, game_frontend/src/redux/features/Analytics/index.js, game_frontend/src/redux/features/Analytics/index.test.js, game_frontend/src/redux/features/index.js
Added `hasAnalyticsCookiesConsent` function which checks for the Analytics consent in OneTrust. This is used around ReactGA calls, blocking them if the consent is false.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1511)
=> feat: block GA if there's no consent

.github/workflows/publish-docker-images.yml
Tested the following on push:
```
- name: Test trigger dev deployment
uses: actions/github-script@v4
with:
github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
script: |
github.actions.createWorkflowDispatch({
owner: 'ocadotechnology',
repo: 'codeforlife-deploy-appengine',
workflow_id: 'deploy_dev.yml',
ref: 'debug-ratelimit',
});
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1523)
=> fix: trigger staging deployment using actions

Pipfile.lock, game_frontend/public/handlebars_template.html, game_frontend/src/components/GameView/__snapshots__/index.test.js.snap, game_frontend/src/components/GameView/index.js, game_frontend/src/components/GameView/index.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1546)
=> fix: Use Freshdesk widget in load screen

aimmo/worksheets.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1630)
=> fix: remove unused worksheet fields

.github/workflows/ci.yml, Pipfile, Pipfile.lock, aimmo-game-creator/Dockerfile, aimmo-game-worker/Dockerfile, aimmo-game-worker/Pipfile, aimmo-game-worker/Pipfile.lock, aimmo-game/Dockerfile, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1632)
=> fix: cleanup ci and update pipfile

aimmo-game/simulation/worksheet/avatar_state_serializers.py, aimmo-game/simulation/worksheet/worksheet.py, aimmo-game/tests/test_simulation/worksheet/test_avatar_state_serializers.py, aimmo/tests/test_views.py, aimmo/worksheets.py, pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1651)
=> feat: add worksheet 4

game_frontend/src/pyodide/badges.test.ts, game_frontend/src/pyodide/badges.ts, game_frontend/src/pyodide/pyodideRunner.ts, game_frontend/src/redux/features/AvatarWorker/epics.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1774)
=> fix: revert changes

.github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1790)
=> build: Fix semantic release < 8

aimmo/worksheets.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1792)
=> fix: Kurono code changes in game and starter/hint code

.codecov.yml, game_frontend/src/pyodide/syntax.test.ts, game_frontend/src/pyodide/syntax.ts, game_frontend/src/pyodide/webWorker.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1838)
=> feat: validate imports
