README.md
=> Add some details about where the components are stored

players/migrations/0002_auto_20160601_1914.py, players/models.py, players/static/js/program.js, players/views.py
Don't require users to have gone through the registration screen.
Allows ones from `createsuperuser` etc.
=> Create the `Player` object on-demand

aimmo-game/simulation/world_map.py
Can see this working if you change the map size (in aimmo-game service.py to start out at 3 by 3 and spinning up a couple of instances)
=> World map now expands in two directions (both away from 0,0)

run.py
Fixes bug where run.py fails on a new install or cleared DB.
=> Migrate DB before trying to operate on it.

README.md, all_tests.py, run.py
* Script that runs `python setup.py test` for each app.
* Add shebang to run.py.
=> Add script to run all tests

.gitignore, aimmo-game-creator/setup.py, aimmo-game-worker/setup.py, aimmo-game/setup.py, setup.py
* PEP8 requirements for setup.py
* Correct names in setup.py
* pep8.txt is generated by tests so should not be checked in
=> Cleanup project setup.py and add pep8.txt to .gitignore.

run.py
Need to download Django from pip before trying to import it.
=> Fix error on first use or run.py.

.travis.yml, README.md, all_tests.py
Script now has option to generate coverage. This is used by travis/coveralls.
=> Add coverage data

aimmo-game/service.py, aimmo-game/simulation/avatar/avatar_wrapper.py
Logs that an error occurs (as usefully as possible) then set action to Wait.
=> Default to WaitAction if polling worker fails. Fixes #142.

aimmo-reverse-proxy/nginx.conf
Previously only the XHR fallback was working.
=> Fix WebSocket connections

.gitignore, README.md, aimmo-game-creator/rc-aimmo-game-creator.yaml, aimmo-game-creator/service.py, aimmo-game/simulation/worker_manager.py, example_project/example_project/settings.py, minikube.py, players/app_settings.py, run.py
=> Add script to run minikube

players/static/css/program.css, players/static/js/program.js, players/templates/players/program.html
Added live autocomplete with tooltips
=> Improve code editor

aimmo-game-worker/tests/simulation/test_world_map.py, aimmo-game/service.py, aimmo-game/simulation/avatar/fog_of_war.py, aimmo-game/simulation/map_generator.py, aimmo-game/simulation/world_map.py, aimmo-game/tests/simulation/maps.py, aimmo-game/tests/simulation/test_map_generator.py, aimmo-game/tests/simulation/test_turn_manager.py, aimmo-game/tests/simulation/test_world_map.py, aimmo-game/tests/test_service.py, players/static/js/watch/world-controls.js, players/static/js/watch/world-viewer.js
Map is now centred on origin and will expend in all four compass directions (always adds all four sides each expansion).
=> Expand in 4-directions

aimmo-game/service.py, example_project/example_project/settings.py, minikube.py, minikube_requirements.txt, players/views.py, run.py
@Spycho Can you take a look, and see if this works for you?
=> Fix minikube build

.gitattributes, aimmo-game-worker/run.sh, minikube_requirements.txt
Fixes required to get local kubernetes (minikube) working on Windows, as discovered through debugging with @mikebryant today.
=> Kubernetes on windows fixes

aimmo-game/simulation/worker_manager.py
Otherwise multiple games will use the same port range and clash
Fixes #209
=> Use a different set of ports per game

aimmo-game/tests/test_service.py, aimmo-game/tests/test_simulation/maps.py, integration-tests/tests/simulation.py
Fixed the merge confilicts resulted from mergeing at the same time.
=> Fix merge conflicts #222, #223

README.md
=> README.md contact link fix

aimmo-game-worker/simulation/direction.py, aimmo-game-worker/tests/simulation/test_action.py, aimmo-game-worker/tests/simulation/test_avatar_state.py, aimmo-game-worker/tests/simulation/test_direction.py, aimmo-game-worker/tests/simulation/test_event.py
Wrote some tests while reading the codebase. Should be close to 80% coverage now.
=> Extra Tests

aimmo-game/tests/test_simulation/test_game_state.py
Fixes #260 and I refactored the code because the one previously didn't really serve much purpose.
=> Test_game_state unused code 

aimmo-game/simulation/effects.py, aimmo-game/simulation/pickups.py, aimmo-game/tests/test_simulation/test_effects.py, aimmo-game/tests/test_simulation/test_pickups.py
As requested in a previous PR, separate one for name changing.
Also adding the missed functionality that was not merged in last time.
=> Effects / Pickups name change & Constructor change

aimmo-game/simulation/turn_manager.py
PR #329 broke the game because of referencing issues. This should fix it.
=> Quickfix for PR329

aimmo-game/simulation/action.py
I was reading through action and found it hard to read as many functions relate to each other. Therefore very minor changes =)
Please test regardless of how small this is.
=> Action: function declarations with privacy convention

aimmo-game/simulation/effects.py, aimmo-game/tests/functional/test_effect_expiry.py
=> Expiry Tests

aimmo-game/simulation/turn_manager.py
It doesn’t need to be so fast right now!
=> Increase turn interval

aimmo-game/requirements.txt, aimmo-game/service.py, example_project/example_project/settings.py, players/templates/players/watch.html, setup.py
=> Correct URL path port in sockets

README.md
Quick README change to make the setup process a bit easier to understand (as I seen the difficulties in yesterdays session).
=> Update README - minor changes

deploy_dev.py
Deploy script that alters GCP clusters! You need to authenticate locally to run it. Download `google-cloud` to do so.
=> Create a deploy script that runs locally

.gitignore, aimmo_runner/runner.py, game_frontend/.babelrc, game_frontend/README.md, game_frontend/djangoBundler.js, game_frontend/package.json, game_frontend/yarn.lock, players/urls.py
As agreed for this task, this works locally
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/507)
=> Integrate react with django

players/templates/players/base.html, players/templates/registration/success_logout.html, players/urls.py
Closes #509. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/512)
=> Logout functionality for old temp UI

.travis.yml
Using the build stages API from travis (currently in beta) to separate the python job from the game frontend job (and so that they can run in parallel!)
deploys only happen on master now
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/522)
=> CI for frontend!

.travis.yml, setup.py
Fixes #541.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/543)
=> MAKE TRAVIS WORK AGAIN WOOHOOO

game_frontend/package-lock.json, game_frontend/package.json
https://nvd.nist.gov/vuln/detail/CVE-2018-3728
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/550)
=> CVE-2018-3728

players/forms.py, players/management/commands/generate_players.py, players/templatetags/players_utils.py, players/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/556)
=> Remove user list display from new game form

.travis.yml, MANIFEST.in, game_frontend/package.json, game_frontend/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/557)
=> Build react frontend for pypi package

.codeclimate.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/558)
=> Ignore test files and djangoBundler from linting on CodeClimate

players/templates/players/watch.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/560)
=> Fix avatar marker

aimmo_runner/minikube.py, aimmo_runner/runner.py, docs/usage.md
Some small changes and refactoring mainly. Most was non-code. Docs updated so the issue should not happen again. Mainly related to #574.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/577)
=> Mini building docker changes

players/forms.py, players/management/commands/generate_players.py, players/models.py, players/templates/players/add_game.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/578)
=> Change default settings. Solves #567

players/migrations/0007_auto_20180515_1300.py
Adds automatically generated migrations. I suppose we commit them instead of having them part of the CI/CD?
PR in question is #578.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/579)
=> Add migrations (missing in last PR)

aimmo-game-creator/game_manager.py
Sorry for yet another PR, but docker gets updated only on master level.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/592)
=> Fix K8S ingress

players/templates/players/home.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/596)
=> changed the text in home - fixes #595

docs/architecture/workers/README.md
corrected a typo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/623)
=> corrected a typo in the readme

docs/usage.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/648)
=> Update usage.md to differentiate between OS's

aimmo-game/simulation/avatar/avatar_wrapper.py, aimmo-game/tests/functional/test_movements_in_map.py, aimmo-game/tests/test_simulation/dummy_avatar.py, aimmo-game/tests/test_simulation/test_turn_manager.py, docs/architecture/games/actions.md
Adding tests for avatars whose workers have somehow failed or lost connection, and improving the docs to better explain the movement mechanics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/670)
=> New tests for dead avatar

aimmo-game-worker/avatar_runner.py, aimmo-game-worker/service.py, aimmo-game-worker/tests/test_avatar_runner.py
By temporarily changing stdout, the worker now captures any output from the user supplied code and then sends it back to the game pod. Solves https://github.com/ocadotechnology/aimmo/issues/629
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/677)
=> Send logs from worker

aimmo-game-creator/game_manager.py, aimmo-game-creator/service.py, aimmo-game/simulation/avatar/avatar_wrapper.py, aimmo-game/simulation/game_logic/spawn_location_finder.py, aimmo-game/simulation/map_generator.py, aimmo-game/tests/functional/mock_world.py, aimmo-game/tests/functional/test_invulnerability_pickups_and_effects.py, aimmo-game/tests/functional/test_movements_in_map.py, aimmo-game/tests/test_simulation/avatar/test_avatar_wrapper.py, aimmo-game/tests/test_simulation/dummy_avatar.py, aimmo-game/tests/test_simulation/test_avatar_location.py, aimmo-game/tests/test_simulation/test_cell.py, aimmo-game/tests/test_simulation/test_turn_manager.py, aimmo-game/tests/test_simulation/test_world_map.py, aimmo/tests/tests.py, aimmo/urls.py, aimmo_runner/shell_api.py, docs/architecture/games/actions.md
Just some small changes to try to improve our CodeClimate rating.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/672)
=> Minor PEP8 changes

aimmo-game/service.py, aimmo-game/simulation/game_state_provider.py, aimmo-game/simulation/logs_provider.py, aimmo-game/simulation/turn_manager.py, aimmo-game/tests/functional/mock_world.py, aimmo-game/tests/test_service.py, aimmo-game/tests/test_simulation/fake_game_runner.py, aimmo-game/tests/test_simulation/test_turn_manager.py
This PR is pretty much the same as #707. Everything is documented there. Unfortunately I got caught out by Python...
[Here's the reason](https://docs.python-guide.org/writing/gotchas/):
> Python’s default arguments are evaluated once **when the function is defined, not each time the function is called** (like it is in say, Ruby). This means that if you use a mutable default argument and mutate it, you will and have mutated that object for all future calls to the function as well.
The default parameter was being set at definition time, meaning that the class wide variable set to `None` was actually not working correctly and we couldn't figure what's wrong for a while. I reverted `feature/guessLogs` branch to a working state, made the fix and now pushing the whole thing together again. Most …
=> Leaking data structures + gotcha fix

game_frontend/package.json, game_frontend/src/index.js, game_frontend/src/redux/api/get.js, game_frontend/src/redux/api/post.js, game_frontend/src/redux/api/socket.js, game_frontend/src/redux/api/socket.test.js, game_frontend/src/redux/api/unity.js, game_frontend/src/redux/features/Editor/epics.js, game_frontend/src/redux/features/Editor/epics.test.js, game_frontend/src/redux/features/Game/epics.js, game_frontend/src/redux/features/Game/epics.test.js, game_frontend/src/redux/features/GhibliMovies/epics.js, game_frontend/src/redux/features/GhibliMovies/epics.test.js, game_frontend/src/redux/store.js, game_frontend/src/setupTests.js, game_frontend/yarn.lock
- Also upgraded redux and redux-observable so they are compatible with the new version of rxjs.
- Fixed imports
- Store in epics has been replaced with state
- Tests no longer using mockStore()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/740)
=> Upgrade rxjs to version 6

Pipfile, Pipfile.lock
Adds pylint as a dev requirement to the pip environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/752)
=> Add pylint to Pipfile and Pipfile.lock

game_frontend/src/components/IDEConsole/index.js
Fixes #749.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/751)
=> Fix #749 | Scrolling bug

aimmo/urls.py, game_frontend/djangoBundler.js, game_frontend/package.json, game_frontend/src/index.js, game_frontend/yarn.lock
Have a look at #758.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/759)
=> Polyfill for IE11 + removing socketio cdn

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/761)
=> Update README.md to include Zenhub.

aimmo/admin.py
This changes the admin display of Game, showing you the game id and name on the main page. Clicking on a game's id will then list all the players currently in the game at the bottom of the page. 
If anyone would like to see how it looks then you can test locally on the admin page after you switch to this branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/782)
=> Changed admin display of Game

aimmo-game-worker/avatar_runner.py, aimmo-game-worker/tests/test_avatar_runner.py
Fixes https://github.com/ocadotechnology/aimmo/issues/788.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/790)
=> Fix the bug where the code updated flag is sent too often for code with syntax errors. 

setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/739)
=> update to Django 1.10

aimmo-game-worker/avatar_runner.py, aimmo-game-worker/tests/test_avatar_runner.py
Fixes #795
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/796)
=> Fix syntax errors dissapearing

aimmo-game-creator/game_manager.py, aimmo-game/simulation/worker_managers/local_worker_manager.py, aimmo-game/tests/test_simulation/worker_managers/test_local_worker_manager.py
workers in separate games were listening on the same ports, causing them to share actions. Added a fix to prevent the conflicting ports.
Fix: https://github.com/ocadotechnology/aimmo/issues/738
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/798)
=> Local mode games not working

aimmo/avatar_examples/dumb_avatar.py
I forgot to return an action in the AI:MMO code and only realised after it deployed to dev :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/816)
=> Return an action in default AI:MMO code

docs/usage.md
Update the usage instructions to reflect the fact that there now exists a setup script (for mac and ubuntu users only at this time). The usage instructions have also been updated to provide a more comprehensive set of setup instructions to the individual, by splitting up the process into the individual operating systems currently catered for.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/827)
=> Update usage instructions

aimmo/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/841)
=> Fix owner naming on the Avatar Data admin page

aimmo/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/851)
=> trying to find where the avatar admin display is breaking

aimmo_runner/minikube.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/861)
=> Merge master into development

aimmo-game-worker/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/879)
=> Update docker command to fix port issue

docs/deployment/deployment-events.md
- Updated current content to reflect migration to codecov.
- Added section detailing the process for deploying AI:MMO to production (basically just clarifying that a PR needs to be made from development into master).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/960)
=> Updated deployment details

docs/deployment/grafana-persistence.md
Before, the doc for Grafana persistence was located on the wiki. It has now been added to the `docs` folder on aimmo as well, this also helps with things like version control.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/965)
=> Add Grafana persistence doc

aimmo-game/authentication.py, aimmo-game/service.py, aimmo-game/tests/test_authentication.py
fixed some import errors and added some tests. Solves the issues found [here](https://console.cloud.google.com/errors/CN-j7MWd94__igE?service=gke_instances&time=P1D&project=decent-digit-629).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1032)
=> Fix token generation

.travis.yml, aimmo-game-worker/simulation/world_map.py, aimmo-game-worker/tests/tests_simulation/test_world_map.py, aimmo-game/Pipfile, aimmo-game/Pipfile.lock, aimmo-game/simulation/workers/worker.py, aimmo-game/tests/test_simulation/avatar/test_avatar_wrapper.py, aimmo-game/tests/test_simulation/workers/test_worker.py
Travis builds would pass even if we had failing tests (because the containers would run successfully), this was then fixed and revealed failing tests, which are now working again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1083)
=> Fix slient fail on tests

.travis.yml, version_updater.py
The TRAVIS_BUILD_NUMBER arg was typed as a string but it should be an integer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1132)
=> ci: update travis build number arg type to int

.travis.yml, version_updater.py
Trying to parse the arguments without specifying their type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1133)
=> ci: remove types from args

.travis.yml, version_updater.py
Adds a tag creation in version updater to make publish command work
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1136)
=> ci: add tag creation in release stage

.travis.yml, version_updater.py
Before, the semantic-release publish command was called within a bundler stage. This should be in its own stage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1138)
=> ci: add stage for semantic release publishing

.travis.yml, aimmo/__init__.py
This PR tweaks the stage conditions so that the tests only run in PR builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1150)
=> fix: make tests run only in PRs

aimmo/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1153)
=> fix: sync version once more to be synced with tags

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1157)
=> fix: bundle frontend before release

aimmo/__init__.py
Our semantic release fork hadn't been writing the new versions to the __init.py__ file properly for a while. This PR syncs the version to make sure it's up to date.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1164)
=> fix: manually sync version with latest tag on development

aimmo/__init__.py, aimmo/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1165)
=> fix: Sync version to match tag

aimmo/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1166)
=> fix: Sync project version to match tag

aimmo/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1167)
=> fix: Sync project version to match tag after semantic release fix

aimmo-game/simulation/interactables/__init__.py, aimmo-game/simulation/simulation_runner.py, aimmo-game/tests/test_service.py, aimmo-game/tests/test_simulation/test_simulation_runner.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1178)
=> feat: Disable interactables

aimmo-game/activity_monitor.py, aimmo-game/service.py, aimmo-game/simulation/game_runner.py, aimmo-game/simulation/worker_manager.py, aimmo-game/simulation/workers/worker.py, aimmo-game/tests/test_simulation/concrete_worker.py, aimmo-game/tests/test_simulation/mock_worker_manager.py, aimmo-game/tests/test_simulation/workers/test_local_worker.py, aimmo-game/tests/test_socketio.py, aimmo/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1183)
=> Release 0.31.1

game_frontend/src/components/GameView/__snapshots__/index.test.js.snap, game_frontend/src/components/GameView/index.js
This PR repositions the compass in its original place. This is to fix a mistake that was done in a previous commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1203)
=> fix: reposition compass correctly

aimmo/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1211)
=> build: Set version to correct one

aimmo/__init__.py, game_frontend/package.json, game_frontend/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1214)
=> Release 0.34.1

aimmo/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1220)
=> build: Merge master into dev

CONTRIBUTING.md, docs/life-cycle-of-a-code-change.md
Added document listing the pipeline a code change undergoes from a local branch to production.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1217)
=> docs: added life cycle of a code change doc

CONTRIBUTING.md, aimmo/__init__.py, docs/life-cycle-of-a-code-change.md, game_frontend/package.json, game_frontend/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1225)
=> Release 0.34.3

aimmo/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1226)
=> build: merge master into development

.travis.yml
I'm making this a fix version so that I can test that it is working fully (it needs a release)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1227)
=> fix: Merge dev into master automatically

.travis.yml, Pipfile.lock, aimmo/__init__.py, aimmo/admin.py, aimmo/game_renderer.py, aimmo/models.py, aimmo/permissions.py, aimmo/serializers.py, aimmo/tests/test_migration_alter_game_token.py, aimmo/tests/test_migration_game_status.py, aimmo/tests/test_views.py, aimmo/views.py, aimmo_runner/docker_scripts.py, aimmo_runner/minikube.py, aimmo_runner/runner.py, aimmo_runner/shell_api.py, aimmo_setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1230)
=> Release 0.35.0

.travis.yml
This PR makes the 'Merge master into development after release' stage run when there is a tag and that tag is a master release tag. This is done by checking if the tag does not contain a "b" character.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1232)
=> fix: Fix conditions for automatic master merge stafe

.travis.yml, aimmo/__init__.py, game_frontend/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1233)
=> Release 0.35.2

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1234)
=> fix: add 'v' to release regex

.travis.yml, aimmo/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1236)
=> Release 0.35.3

Pipfile.lock, aimmo/templates/players/add_game.html, example_project/example_project/settings.py, setup.py
Only used on the add game form used for local development
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1237)
=> fix: Remove django forms bootstrap and usage

Pipfile.lock, aimmo/__init__.py, aimmo/templates/players/add_game.html, example_project/example_project/settings.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1238)
=> Release 0.35.4

aimmo/setup.py, setup.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1242)
=> fix: Remove httmock and mock

Pipfile, Pipfile.lock, aimmo/__init__.py, aimmo/setup.py, aimmo_runner/runner.py, integration_tests/setup.py, minikube_requirements.txt, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1243)
=> Release 0.35.6

aimmo-game/simulation/game_runner.py, aimmo-game/tests/test_simulation/test_world_map.py, aimmo-game/tests/test_simulation/workers/test_worker.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1247)
=> fix: Fix turn offset error

.travis.yml, Pipfile, integration_tests/tests/test_integration.py, integration_tests/tests/test_kubernetes.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1249)
=> fix: Upgrade travis and Pipfile to use Python 3.6.7

aimmo-game/simulation/game_runner.py, aimmo-game/simulation/game_state.py, aimmo-game/simulation/simulation_runner.py, aimmo-game/simulation/worker_manager.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1252)
=> fix: Await worker data fetch

aimmo-game/tests/test_simulation/test_worker_manager.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1257)
=> fix: Add test for turn offset bug

aimmo-game/simulation/game_runner.py, aimmo-game/simulation/game_state.py, aimmo-game/simulation/simulation_runner.py, aimmo-game/simulation/worker_manager.py, aimmo-game/tests/test_simulation/test_worker_manager.py, aimmo/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1254)
=> Release 0.36.2

aimmo-game/simulation/worker_manager.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1263)
=> fix: Catch timeout error when fetching worker data

aimmo-game/simulation/worker_manager.py, aimmo/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1264)
=> Release 0.36.3

aimmo-game-worker/avatar_runner.py, aimmo-game-worker/code_updater.py, aimmo-game-worker/service.py, aimmo-game-worker/simulation/action.py, aimmo-game-worker/simulation/avatar_state.py, aimmo-game-worker/simulation/event.py, aimmo-game-worker/simulation/world_map.py, aimmo-game-worker/tests/test_avatar_runner.py, aimmo-game-worker/tests/tests_simulation/test_world_map.py, aimmo-game/simulation/avatar/avatar_wrapper.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1266)
=> feat: Add artefact logic to worker

aimmo-game/simulation/worker_manager.py, aimmo-game/simulation/workers/worker.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1268)
=> fix: Make more helpful error messages

aimmo-game/service.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1269)
=> fix: Cors headers for servers should be https

aimmo-game/service.py, game_frontend/src/components/GameView/__snapshots__/index.test.js.snap, game_frontend/src/components/GameView/index.js, game_frontend/src/components/GameView/index.test.js, game_frontend/src/components/LogEntries/__snapshots__/index.test.js.snap, game_frontend/src/components/LogEntries/index.js, game_frontend/src/containers/IDEConsole/__snapshots__/index.test.js.snap, game_frontend/src/containers/IDEConsole/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1270)
=> fix: Fix console log bug hiding code

aimmo-game/service.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1273)
=> fix: Fix production domain in allowed CORS

aimmo-game/service.py, aimmo/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1274)
=> Release 0.39.4

aimmo/admin.py, aimmo/game_creator.py, aimmo/game_renderer.py, aimmo/views.py
This PR refactors the logic when a game created.
This is too facilitate the import of this method in portal, which is where the source of this bug lies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1277)
=> fix: Refactor game creation logic

aimmo/__init__.py, aimmo/admin.py, aimmo/game_creator.py, aimmo/game_renderer.py, aimmo/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1278)
=> Release 0.39.5

.travis.yml, aimmo/__init__.py, aimmo_runner/runner.py, game_frontend/djangoBundler.js, game_frontend/public/handlebars_template.html, game_frontend/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1282)
=> Release 0.39.6

aimmo/__init__.py, game_frontend/src/babylon/environment/index.ts, game_frontend/src/components/GameView/__snapshots__/index.test.js.snap, game_frontend/src/components/GameView/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1286)
=> Release 0.39.7

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1296)
=> build: Add group setting back to Travis

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1297)
=> build: Remove language spec from Release stage

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1299)
=> build: Install node 12 also in Release stage

game_frontend/src/babylon/entities/avatarManager.ts, game_frontend/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1304)
=> fix: Make attachMarker def async

aimmo/__init__.py, game_frontend/src/babylon/entities/avatarManager.ts, game_frontend/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1305)
=> Release 0.42.2

game_frontend/package.json, game_frontend/yarn.lock
* fix: game_frontend/package.json & game_frontend/yarn.lock to reduce vulnerabilities
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-JS-HANDLEBARS-567742
* fix: game_frontend/package.json & game_frontend/yarn.lock to reduce vulnerabilities
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-JS-HANDLEBARS-567742
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1323)
=> fix: Security upgrade handlebars from 4.5.3 to 4.6.0 (merge master into dev)

.travis.yml, publish_aimmo_avatar_api.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1328)
=> fix: error in travis scripts for publishing avatar api package 

.travis.yml
This stops travis releasing the package twice which stops a versioning issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1329)
=> fix: Publish aimmo-avatar-api package on deploy

.travis.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1330)
=> fix: install twine on deploy step for avatar_api package

game_frontend/package.json, game_frontend/src/components/GameView/index.js, game_frontend/src/components/IDE/index.js, game_frontend/src/components/LogEntries/index.js, game_frontend/src/components/LogEntries/index.test.js, game_frontend/src/containers/IDEConsole/__snapshots__/index.test.js.snap, game_frontend/src/containers/IDEConsole/index.js, game_frontend/src/containers/IDEConsole/index.test.js, game_frontend/src/index.js, game_frontend/src/redux/features/Analytics/index.js, game_frontend/src/redux/features/Analytics/reducers.js, game_frontend/src/redux/features/ConsoleLog/reducers.js, game_frontend/src/redux/features/ConsoleLog/reducers.test.js, game_frontend/src/redux/features/index.js, game_frontend/src/setupTests.js, game_frontend/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1348)
=> fix: Logs for current turn now show as soon as `next_turn` is computed

aimmo-game/Pipfile, aimmo-game/Pipfile.lock, aimmo-game/service.py, aimmo-game/setup.py, aimmo-game/simulation/django_communicator.py, aimmo-game/tests/conftest.py, aimmo-game/tests/test_simulation/mock_communicator.py, aimmo-game/tests/test_simulation/test_django_communicator.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1370)
=> fix: use json instead of read on response

game_frontend/package.json, game_frontend/src/babylon/environment/environment.ts, game_frontend/yarn.lock
Tested on the latest version of Chrome and Firefox at the time of writing. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1377)
=> fix: Update babylonjs to 4.1

game_frontend/src/babylon/entities/avatarManager.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1384)
=> fix: Increase size of avatar and marker

.github/workflows/cypress.yml, aimmo-game/simulation/django_communicator.py, aimmo/__init__.py, game_frontend/cypress/integration/avatarWorker/codeExecution.spec.js, game_frontend/cypress/integration/avatarWorker/webWorker.spec.ts, game_frontend/cypress/plugins/index.js, game_frontend/cypress/support/avatarCodeTester.ts, game_frontend/cypress/support/commands.ts, game_frontend/cypress/support/index.js, game_frontend/djangoBundler.js, game_frontend/package.json, game_frontend/public/handlebars_template.html, game_frontend/public/index.html, game_frontend/src/babylon/entities/avatarManager.ts, game_frontend/src/index.js, game_frontend/src/pyodide/computedTurnResult.ts, game_frontend/src/pyodide/pyodideRunner.ts, game_frontend/src/pyodide/webWorker.test.ts, game_frontend/src/pyodide/webWorker.ts, game_frontend/src/redux/features/AvatarWorker/epics.js, game_frontend/src/redux/features/AvatarWorker/epics.test.js, game_frontend/src/redux/features/AvatarWorker/index.js, game_frontend/src/redux/features/AvatarWorker/operators.js, game_frontend/src/redux/features/AvatarWorker/reducers.js, game_frontend/src/redux/features/index.js, game_frontend/tsconfig.json, game_frontend/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1385)
=> Release 0.56.0

.github/workflows/cypress.yml, aimmo/__init__.py, aimmo/game_creator.py, aimmo/tests/test_views.py, aimmo_runner/runner.py, aimmo_setup.py, docs/usage.md, game_frontend/cypress.json, game_frontend/cypress/integration/avatarWorker/codeExecution.spec.js, game_frontend/cypress/integration/avatarWorker/webWorker.spec.ts, game_frontend/cypress/support/commands.ts, game_frontend/cypress/support/index.d.ts, run.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1402)
=> Release 0.58.3

game_frontend/package.json, game_frontend/src/components/IDE/__snapshots__/index.test.js.snap, game_frontend/src/components/LogEntries/__snapshots__/index.test.js.snap, game_frontend/src/components/LogEntries/index.js, game_frontend/src/containers/IDEConsole/__snapshots__/index.test.js.snap, game_frontend/src/containers/IDEConsole/index.js, game_frontend/src/testHelpers/createMount.js, game_frontend/src/testHelpers/createShallow.js, game_frontend/yarn.lock
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1407)
=> fix: Update styled-components

.codeclimate.yml, .gitignore, Pipfile.lock, aimmo/tests/test_views.py, game_frontend/cypress/integration/user/navigation.spec.js, game_frontend/cypress/support/commands.ts, game_frontend/public/handlebars_template.html, game_frontend/src/components/NavigationBar/__snapshots__/index.test.js.snap, game_frontend/src/components/NavigationBar/index.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1411)
=> feat: add "exit button" to game

.codeclimate.yml, .gitignore, Pipfile.lock, aimmo/__init__.py, aimmo/tests/test_views.py, game_frontend/cypress/integration/user/navigation.spec.js, game_frontend/cypress/support/commands.ts, game_frontend/package.json, game_frontend/public/handlebars_template.html, game_frontend/src/components/IDE/__snapshots__/index.test.js.snap, game_frontend/src/components/LogEntries/__snapshots__/index.test.js.snap, game_frontend/src/components/LogEntries/index.js, game_frontend/src/components/NavigationBar/__snapshots__/index.test.js.snap, game_frontend/src/components/NavigationBar/index.js, game_frontend/src/containers/IDEConsole/__snapshots__/index.test.js.snap, game_frontend/src/containers/IDEConsole/index.js, game_frontend/src/testHelpers/createMount.js, game_frontend/src/testHelpers/createShallow.js, game_frontend/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1410)
=> Release 0.61.0

.github/workflows/cicd.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1429)
=> fix: attempt github.event.head_commit.author.email

.github/workflows/cicd.yml, .github/workflows/publish-docker-images.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1431)
=> fix: cleanup github actions

CHANGELOG.md, aimmo/__init__.py, aimmo/forms.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1432)
=> Release 0.61.7

.github/workflows/cicd.yml
Run tests on all commits on develop and master so codecov will have a base to compare with
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1436)
=> fix: remove github action check on tests

setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1437)
=> fix: Don't fix cfl-common version

.github/workflows/cicd.yml, Pipfile, Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1440)
=> fix: Remove build dependencies

.github/workflows/cicd.yml, CHANGELOG.md, Pipfile, Pipfile.lock, aimmo/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1441)
=> Release 0.61.10

aimmo/serializers.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1446)
=> fix: Make worksheet editable in serializer

.github/workflows/cicd.yml, Pipfile.lock, aimmo/migrations/0024_unique_class_per_game.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1451)
=> fix: cleanup add game dropdown

Pipfile.lock, aimmo/serializers.py, aimmo/tests/test_views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1454)
=> fix: Update game's avatars with worksheet's code on change

CHANGELOG.md, Pipfile.lock, aimmo/__init__.py, aimmo/serializers.py, aimmo/tests/test_views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1455)
=> Release 0.62.2

aimmo/serializers.py, aimmo/tests/test_views.py, aimmo/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1456)
=> feat: Delete multiple games

CHANGELOG.md, aimmo/__init__.py, aimmo/serializers.py, aimmo/tests/test_views.py, aimmo/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1457)
=> Release 0.63.0

aimmo/migrations/0024_unique_class_per_game.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1458)
=> fix: create and drop temp table in migration

CHANGELOG.md, aimmo/__init__.py, aimmo/migrations/0024_unique_class_per_game.py
* fix: create and drop temp table in migration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1459)
=> Release 0.63.1

aimmo-game-creator/game_manager.py, aimmo-game-creator/tests/test_game_manager.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1474)
=> fix(game-creator): catch exc when removing path

aimmo-game-creator/game_manager.py, aimmo-game-creator/tests/test_game_manager.py, aimmo-game/service.py
Game settings are now set in the annotation of the allocation by the game creator and will later be fetched by the game. This should fix the pickups not showing on the map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1477)
=> fix: show pickups on map

CHANGELOG.md, aimmo-game-creator/game_manager.py, aimmo-game-creator/tests/test_game_manager.py, aimmo-game/service.py, aimmo/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1478)
=> Release 0.65.4

setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1491)
=> fix: require kubernetes

CHANGELOG.md, aimmo/__init__.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1492)
=> Release 0.67.2

aimmo-game-worker/setup.cfg, aimmo-game-worker/setup.py, aimmo-game-worker/tests/tests_simulation/test_avatar_state.py, aimmo-game-worker/tests/tests_simulation/test_world_map.py, aimmo_runner/build_worker_wheel.sh, game_frontend/cypress/support/commands.ts, game_frontend/src/pyodide/webWorker.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1497)
=> fix: update unit tests to pytest

aimmo-game-worker/simulation/action.py, aimmo-game-worker/simulation/world_map.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1498)
=> fix: wrap artefact in namedtuple

.codecov.yml, .github/workflows/cicd.yml, CONTRIBUTING.md, aimmo_runner/runner.py, game_frontend/cypress/fixtures/gameState.json, game_frontend/cypress/support/avatarCodeTester.ts, game_frontend/cypress/support/commands.ts, game_frontend/package.json, game_frontend/src/index.js, game_frontend/yarn.lock
- upgrade cypress version to 7.x
- update default browser to chrome
- fix cypress tests
- GA to be triggered only on production
- update codecov ignore list
- remove travis references
- update to contributing section
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1510)
=> fix: upgrade cypress version to 7.x plus test updates

aimmo-game/setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1514)
=> fix: downgrade pytest-asyncio for tests

CHANGELOG.md, aimmo/__init__.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1515)
=> Release 0.69.2

game_frontend/cypress.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1516)
=> ci: disable video upload when cypress tests pass

game_frontend/src/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1517)
=> fix: trigger GA only on production

CHANGELOG.md, aimmo/__init__.py, game_frontend/cypress.json, game_frontend/src/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1518)
=> Release 0.69.3

Pipfile.lock, game_frontend/cypress/support/commands.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1522)
=> fix: update tests with new teacher login form

game_frontend/package.json, game_frontend/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1532)
=> build(deps): bump browserslist from 4.16.3 to 4.16.6 in /game_frontend

CHANGELOG.md, Pipfile.lock, aimmo/__init__.py, game_frontend/cypress/integration/avatarWorker/codeExecution.spec.js, game_frontend/cypress/integration/avatarWorker/webWorker.spec.ts, game_frontend/cypress/integration/user/actions.spec.js, game_frontend/cypress/integration/user/navigation.spec.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1538)
=> Release 0.69.8

CHANGELOG.md, Pipfile.lock, aimmo/__init__.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1539)
=> Release 0.69.9

Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1541)
=> fix: Update lockfile - Django 2.2.22

CHANGELOG.md, Pipfile.lock, aimmo/__init__.py, aimmo/migrations/0022_allow_games_to_have_no_name.py, aimmo/migrations/0023_remove_level_attempt.py, aimmo/templatetags/players_utils.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1543)
=> Release 0.69.11

Pipfile.lock, game_frontend/public/handlebars_template.html, game_frontend/src/components/GameView/__snapshots__/index.test.js.snap, game_frontend/src/components/GameView/index.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1545)
=> fix: Add more informative game load text

aimmo-game-creator/game_manager.py, aimmo-game-creator/tests/test_game_manager.py, aimmo/tests/test_views.py, aimmo/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1547)
=> fix: improve game load time

.github/workflows/cicd.yml, aimmo_runner/runner.py, example_project/manage.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1558)
=> fix: fix local run (intro in #1556)

Pipfile.lock, game_frontend/cypress/support/commands.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1562)
=> fix: Remove captcha from tests

aimmo/tests/test_views.py
This will fix the tests after deploying the portal change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1566)
=> feat: Remove teacher title

Pipfile.lock, aimmo_setup.py, game_frontend/cypress/support/commands.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1584)
=> fix: fixed setup script, including cmdtest and init docker repo

.github/workflows/cicd.yml, Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1589)
=> fix: tidy up remove worksheet model

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1591)
=> docs: change play/kurono links in readme

aimmo/worksheets.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1592)
=> fix: Replace PDF names with Gitbook links

setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1595)
=> fix: Upgrade Django to 2.2.25

aimmo/worksheets.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1599)
=> fix: Update worksheet 2 starter code to contain task 1

.github/workflows/cicd.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1608)
=> fix: temp CI to install latest portal

aimmo-game-creator/game_manager.py, aimmo-game/Pipfile, aimmo-game/Pipfile.lock, aimmo-game/setup.py, aimmo/game_manager.py, aimmo/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1610)
=> fix: change worksheet

aimmo/worksheets.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1617)
=> fix: update starter code for worksheet 3

.github/workflows/ci.yml, .github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1626)
=> fix: Simplify CI flow and use master only

.github/workflows/ci.yml, .github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1627)
=> fix: Re-add env setting

game_frontend/.eslintrc.js, game_frontend/cypress/integration/avatarWorker/codeExecution.spec.js, game_frontend/package.json, game_frontend/src/global.d.ts, game_frontend/src/pyodide/webWorker.ts, game_frontend/src/redux/features/AvatarWorker/operators.js, game_frontend/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1642)
=> fix: Try updating Pyodide

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1645)
=> fix: Fix indentation in readme code

.github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1646)
=> fix: Upgrade semantic-release version in action

Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1647)
=> build: Update lockfile (Django 3.2.13)

aimmo-game-worker/simulation/avatar_state.py, aimmo-game-worker/simulation/backpack.py, aimmo-game-worker/tests/tests_simulation/test_avatar_state.py, aimmo-game-worker/tests/tests_simulation/test_backpack.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1657)
=> feat: add backpack with find method

aimmo-game/Pipfile.lock, aimmo-game/setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1659)
=> fix: pin grpcio in aimmo-game

aimmo-game/Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1662)
=> fix: re-lock pipfile in aimmo-game

aimmo/worksheets.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1663)
=> fix: add worksheet 4 student challenge url

aimmo-game-worker/simulation/action.py, aimmo-game/simulation/action.py, aimmo-game/tests/test_simulation/test_action.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1669)
=> feat: add message when move towards is rejected

.codecov.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1672)
=> build: Make CodeCov requirement 90%

game_frontend/src/pyodide/badges.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1684)
=> fix: Check if move action on badge 2

Pipfile.lock
This is mostly to test publishing the Docker images.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1691)
=> fix: update pipfile.lock

.github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1692)
=> fix: use our fork of sematic release

Pipfile, Pipfile.lock, aimmo-game-creator/Pipfile, aimmo-game-creator/Pipfile.lock, aimmo-game-creator/tests/test_aimmo_game_creator_yaml.py, aimmo-game-worker/Pipfile, aimmo-game-worker/Pipfile.lock, aimmo-game/Pipfile, aimmo-game/Pipfile.lock, aimmo_setup.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1703)
=> fix: changing worksheet

.github/workflows/ci.yml, README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1711)
=> feat: no feature

aimmo/migrations/0030_update_created_by.py, aimmo/templatetags/players_utils.py, aimmo_setup.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1713)
=> fix: fix created_by migration field

aimmo/templatetags/players_utils.py, aimmo_setup.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1719)
=> fix: Game class show fix

setup.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1721)
=> fix: add kubernetes to setup.py

Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1722)
=> build: Django lockfile 3.2.16

Pipfile, Pipfile.lock, example_project/settings.py, example_project/test_settings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1725)
=> fix: Install django-import-export

.github/workflows/ci.yml, .github/workflows/publish-docker-images.yml, .github/workflows/publish-python-package.yml, .github/workflows/semantic-pull-request-check.yml, .github/workflows/snyk.yml, game_frontend/package.json, game_frontend/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1734)
=> build: Update Github actions

aimmo_runner/runner.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1741)
=> fix: Point to correct settings file locally

.github/workflows/publish-docker-images.yml, .github/workflows/snyk.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1742)
=> fix: Debug github actions

game_frontend/package.json, game_frontend/yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1768)
=> fix: yarn add react-scripts

game_frontend/src/components/NavigationBar/index.js, game_frontend/src/components/NavigationBar/index.test.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1777)
=> fix: Kurono badges trigger

.github/workflows/ci.yml, .github/workflows/publish-python-package.yml, .github/workflows/snyk.yml, Pipfile, Pipfile.lock, aimmo-game-creator/Dockerfile, aimmo-game-creator/Pipfile, aimmo-game-creator/Pipfile.lock, aimmo-game-worker/Dockerfile, aimmo-game-worker/Pipfile, aimmo-game-worker/Pipfile.lock, aimmo-game/Dockerfile, aimmo-game/Pipfile, aimmo-game/Pipfile.lock, game_frontend/src/pyodide/webWorker.test.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1778)
=> feat: Upgrade Python to 3.8

aimmo/serializers.py, aimmo/tests/test_views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1804)
=> fix: Revert worksheet ID type

aimmo-game/Pipfile.lock, aimmo-game/setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1806)
=> fix: Downgrade grpcio

aimmo/migrations/0009_add_game_status.py, aimmo/migrations/0012_auto_20200302_1310.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1822)
=> fix: Fix default status issue

Pipfile.lock, aimmo_runner/setup.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1833)
=> fix: Revert to Django 3.2.22 (CI/CD measuring)

aimmo_runner/setup.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1835)
=> fix: Upgrade to Django 3.2.23 (CI/CD measuring)

aimmo_runner/setup.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1836)
=> build: Downgrade Django (CI/CD measuring)

aimmo_runner/setup.py, setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1837)
=> fix: Upgrade Django to 3.2.23 again (CI/CD measuring)

.github/workflows/publish-docker-images.yml, .github/workflows/publish-python-package.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1844)
=> ci: Replace Razbot with CFLbot

Pipfile, Pipfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ocadotechnology/aimmo/1845)
=> ci: Upgrade setuptools
